### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by swyxio** [eggheadio/gatsby-theme-egghead-blog#7]
this is really great! just want to leave a word of encouragement. coming along nicely! do you mind placing an OSS license on this?

**Comment by texastoland** [comment]
@theianjones @Creeland I've wondered before whether we use a specific license? MIT seems most popular. I prefer Unlicense for simplicity.

**Comment by theianjones** [comment]
thanks @sw-yx its under MIT license :)

**Comment by swyxio** [comment]
nicely done
